# Generated by Django 5.2.12 on 2026-03-06 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('order_index', models.IntegerField()),
                ('status', models.CharField(choices=[('OPEN', 'Открыт'), ('IN_PROGRESS', 'В работе'), ('DONE', 'Выполнен')], default='OPEN', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='projects.project')),
            ],
            options={
                'ordering': ['order_index'],
                'unique_together': {('project', 'order_index')},
            },
        ),
    ]
